markdown: redcarpet
permalink: /:year/:month-:day-:title.html
destination: _site
name: guodakui    #将会显示在左上角
myname: guodakui  #你的名字，显示在页脚和文章开始
email: 791529826@qq.com #邮箱
duoshuo: kevinguodakui #务必改成自己的多说账号或删除此项 
github: seu-guodakui   #github账号，用于构建github链接
project: oschinablog #github上的仓库名
paginate: 20   #每页文章个数
paginate_path: "/blog/page:num/" #此项不可更改
myurl: http://guodakui.oschina.io #此url指向你的首页
baseurl: "" #如果是项目pages，填写为"/<项目名>"
