auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: seu-guodakui
url: http://seu-guodakui.github.io
feed: /atom.xml
author_info: <a href="http://seu-guodakui.github.io/">seu-guodakui</a>
